JustFood/Models/Custom/AddProductView.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace JustFood.Models {
    public class AddProductView {
        
        [DisplayName("Category")]
        [Required]
        public int CategoryID { get; set; }
        
        [Required]
        public int Quantity { get; set; }

        [Required]
        [DisplayName("Quantity Type")]
        public byte QuantityType { get; set; }
        
        [Required]
        public int Cost { get; set; }
    }
}

JustFood/Models/Custom/DiscountView.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace JustFood.Models {
    public class DiscountView {
        [Required]
        public int SaleID { get; set; }
        [Required]
        [DisplayName("Category")]
        public int DiscountCategoryID { get; set; }
        /// <summary>
        /// Sold Price
        /// </summary>
        [DisplayName("Sold Price")]
        [Required, Range(1, 3000)]
        public int Amount { get; set; }
        [Required,MaxLength(20)]
        public String Phone { get; set; }
        [Required,MaxLength(30)]
        public String Name { get; set; }

        [MaxLength(50)]
        public String Notes { get; set; }
        
    }
}

JustFood/Models/Entities/Requisition.cs
using System.ComponentModel;
namespace JustFood.Models {
    public class Requisition {
        public int RequisitionID { get; set; }
        [DisplayName("Type of Requisition")]
        public int CategoryID { get; set; }
        [DisplayName("Quantity")]
        public int Quantity { get; set; }

        /// <summary>
        /// Quantity Type Value
        /// </summary>
        [DisplayName("Quantity Type")]
        public byte QtyType { get; set; }


        public bool IsAutoAdded { get; set; }
        [DisplayName("Is In Process")]
        public bool IsInProcess { get; set; }
        /// <summary>
        /// Processing By whom.
        /// </summary>
        [DisplayName("By Whom")]
        public int? ByWhomUser { get; set; }
        [DisplayName("Is Done")]
        public bool IsDone { get; set; }
        /// <summary>
        /// Added by whom.
        /// </summary>
        [DisplayName("Added By")]
        public int AddedBy { get; set; }

        /// <summary>
        /// List of Quantity types
        /// </summary>
        public virtual QuantityType QuantityType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}

JustFood/Models/Garbage/Requisition.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        public int RequisitionID { get; set; }
        public int CategoryID { get; set; }
        public int Quantity { get; set; }
        public byte QtyType { get; set; }
        public bool IsAutoAdded { get; set; }
        public bool IsInProcess { get; set; }
        public Nullable<int> ByWhomUser { get; set; }
        public bool IsDone { get; set; }
        public int AddedBy { get; set; }
    
        public virtual QuantityType QuantityType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}

JustFood/Areas/Admin/Controllers/ExpenseController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using JustFood.Models;
using JustFood.Modules.Query;

namespace JustFood.Areas.Admin.Controllers {
    public class ExpenseController : Controller {
        private readonly UserInfo _Userinfo = new UserInfo();
        private readonly JustFoodDBEntities db = new JustFoodDBEntities();

        private void GetDropdowns() {
            ViewBag.CategoryProduct = new SelectList(db.Categories.Where(n => n.IsExpense)
                                                       .ToList(), "CategoryID", "Category1");
            ViewBag.AccountOf = new SelectList(db.Users, "UserID", "Name");
        }

        public ActionResult Create() {
            GetDropdowns();
            return View();
        }

        public void CreateExpense(AccountBalance accountbalance) {
            accountbalance.Dated = DateTime.Now;
            accountbalance.AddBy = _Userinfo.GetUserID();
            accountbalance.IsAddedMoney = false;
            accountbalance.IsExpense = true;
            accountbalance.IsBoughtProduct = false;

            if (accountbalance.Amount < 0) {
                ModelState.AddModelError("Amount", "Amount can't be negative.");
            }
            double? sum = db.ViewSummaryAccountBalances.Sum(n => n.Balance);
            if (sum == null) {
                sum = 0;
            }
            var sum2 = (double) sum;
            if (sum2 < accountbalance.Amount) {
                ModelState.AddModelError("Amount", "Sorry your amount excceds your account balance " + sum2 + ".");
            }
            accountbalance.Amount = accountbalance.Amount*-1;

            if (ModelState.IsValid) {
                db.AccountBalances.Add(accountbalance);
                db.SaveChanges();
            }
        }

        [HttpPost]
        public ActionResult Create(AccountBalance accountbalance) {
            if (User.Identity.IsAuthenticated) {
                if (ModelState.IsValid) {
                    CreateExpense(accountbalance);
                    return RedirectToAction("List", "AccountBalance");
                }
            }
            GetDropdowns();
            return View(accountbalance);
        }

        protected override void Dispose(bool disposing) {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

JustFood/Areas/Admin/Controllers/HomeController.cs
using System.Web.Mvc;
using JustFood.Modules.Cache;
using JustFood.Modules.StaticContents;

namespace JustFood.Areas.Admin.Controllers {
    public class HomeController : Controller {
        public HomeController() {
            
        }
        public ActionResult Index() {
            //var tx = Statics.Caches.Get(CacheNames.Sale);
            return View();
        }
    }
}

JustFood/Areas/Sale/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Metadata.Edm;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using JustFood.Modules.Extensions;
using JustFood.Modules.TimeZone;
using Microsoft.Ajax.Utilities;
using DB = JustFood.Models;
using JustFood.Modules.Query;
using JustFood.Modules.Session;
using JustFood.Modules.Cookie;
using JustFood.Modules.Cache;
using JustFood.Models;
using JustFood.Modules.StaticContents;
using JustFood.Modules.Message;
using JustFood.Areas.Admin.Controllers;

namespace JustFood.Areas.Sale.Controllers {
    public class HomeController : Controller {
        readonly DB.JustFoodDBEntities db;
        readonly UserInfo userinfo;
        Exception exceptionNoRights = new Exception("Sorry you have no rights to process this function. Please contact with respective admin for more details.");

        public HomeController() {
            db = new DB.JustFoodDBEntities();
            userinfo = new UserInfo();
        }

        #region Extention Methods and Propertise


        /// <summary>
        /// Check and save current time.
        /// </summary>
        /// <param name="time"></param>
        /// <returns>Checks and returns if times are equal or not from the cookie and then save the cookie.</returns>
        bool IsCookieTimeEqual(string time) {
            string ctime = CookieTime;
            //save current time to cookie.
            CookieTime = time;
            if (ctime != null && time != null && time.Equals(ctime)) {
                return true;
            }
            return false;
        }

        /// <summary>
        /// checks null and return the value.
        /// </summary>
        /// <param name="sale"></param>
        /// <returns></returns>
        bool IsToday(DB.Sale sale) {
            if (sale != null) {
                if (sale.Date.Date == DateTime.Now.Date) {
                    return true;
                }
            }
            return false;
        }

        public String CookieTime {
            get {
                return Statics.Cookies.ReadString(CookiesNames.Time);
            }
            set {
                Statics.Cookies.Save(value, CookiesNames.Time);
            }
        }

        public string CookieIsInventoryEmpty {
            get {
                return Statics.Cookies.ReadString(CookiesNames.InventoryEmpty);
            }
            set {
                Statics.Cookies.Save(value, CookiesNames.InventoryEmpty);
            }
        }


        /// <summary>
        /// Keep only today's sale.
        /// </summary>
        public DB.Sale CacheSale {
            get { return (DB.Sale)Statics.Caches.Get(CacheNames.Sale); }
            set { Statics.Caches.Set(CacheNames.Sale, value); }
        }
        #endregion

        public ActionResult Index() {

            string date = Zone.GetDate(DateTime.Now);

            return View();
        }

        #region Searching

        DB.Sale GetToday() {
            DB.Sale sale;
            sale = CacheSale;
            if (sale != null && IsToday(sale)) {
                try {
                    db.Entry(sale).State = EntityState.Modified;
                } catch (Exception ex) { }
                return sale;
            }
            DateTime date = DateTime.Now.Date;
            sale = db.Sales.FirstOrDefault(n => n.Date == date);
            CacheSale = sale;
            return sale;
        }

        private DB.Sale GetDatedSale(DateTime date) {
            var dated = date.Date;
            DB.Sale sale = CacheSale;
            if (sale != null && IsToday(sale)) {
                try {
                    db.Entry(sale).State = EntityState.Modified;
                } catch (Exception ex) { }
                return sale;
            }
            sale = db.Sales.FirstOrDefault(n => n.Date == dated);
            CacheSale = sale;
            return sale;
        }

        /// <summary>
        /// Will be added with the context.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        private DB.Sale GetDatedSale(int id) {
            DB.Sale sale = CacheSale;
            if (sale != null && IsToday(sale)) {
                try {
                    db.Entry(sale).State = EntityState.Modified;
                } catch (Exception ex) { }
                return sale;
            }
            sale = db.Sales.Find(id);
            CacheSale = sale;
            return sale;
        }

        Inventory GetInventory(int CategoryID) {
            return db.Inventories.FirstOrDefault(n => n.CategoryID == CategoryID);
        }
        #endregion

        #region Quantity Increase & Decrease
        void IncreaseSaleQuantity(DB.DetailedSale dSale, short number = 1) {
            dSale.Qty = number;
        }
        void DecreaseSaleQuantity(DB.DetailedSale dSale, short number = -1) {
            dSale.Qty = number;
        }

        #endregion

        #region Transaction Posibility : if user has permission to do the transaction at current period of time.

        /// <summary>
        /// Returning true means rejected.
        /// Do not execute the transaction.
        /// </summary>
        /// <param name="SaleID"></param>
        /// <returns></returns>
        bool IsTransactionRejected(int SaleID) {
            var user = userinfo.GetUserSession();
            if (user.IsAccessToAdmin) {
                return false;
            }

            var sale = (DB.Sale)Session["Sale"];

            if (sale == null) {
                sale = GetDatedSale(SaleID);
            }
            Session["Sale"] = sale;
            //if date is not valid to today or is already check then return false.
            if (sale.Date.Date != DateTime.Now.Date || sale.IsDiscardsChecked || sale.IsDividedAmongPartners) {
                return true;
            }
            return false;
        }

        bool IsTransactionRejected(DB.Sale sale) {
            var user = userinfo.GetUserSession();
            if (user.IsAccessToAdmin) {
                return false;
            }
            Session["Sale"] = sale;
            //if date is not valid to today or is already check then return true.
            if (sale.Date.Date != DateTime.Now.Date || sale.IsDiscardsChecked || sale.IsDividedAmongPartners) {
                return false;
            }
            return true;
        }

        #endregion
        
        #region First Step: Start Business or Create Daily Sale Ledger

        private int CreateSale(int inHandCash) {
            DB.Sale today = GetToday();
            if (today == null) {
                var sale = new DB.Sale {
                    Date = DateTime.Now,
                    TotalSold = 0,
                    IsDividedAmongPartners = false,
                    OtherExpenses = 0,
                    TotalAcheived = 0,
                    Discount = 0,
                    TotalLess = 0,
                    TotalWastages = 0,
                    TotalDiscountNumber = 0,
                    InHandCashChange = inHandCash,
                    ActualAcheivedFromEmployee = 0,
                    ActualLossProfitAfterCollection = 0,
                    IsInventorySet = false
                };
                db.Sales.Add(sale);
                db.SaveChanges();
                return sale.SaleID;
            } else {
                return today.SaleID;
            }
        }


        ActionResult CreateView() {
            var user = userinfo.GetUser();
            if (user != null && !user.IsAccessToAdmin) {
                return View("Error2", exceptionNoRights);
            }

            return View();
        }

        public ActionResult Create() {
            return CreateView();
        }

        /// <summary>
        /// Save only the cash and start the business.
        /// </summary>
        /// <param name="forms"></param>
        /// <param name="Cash"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(int? Cash) {
            if (Cash == null || Cash <= 0) {
                ModelState.AddModelError("Cash", "Cash can't be negative or zero.");
                return CreateView();
            }
            int saleid = CreateSale((int)Cash);
            db.SaveChanges();
            return RedirectToAction("Today");
        }



        #endregion

        #region Second Step: Setting Inventory & Daily Stock information

        [HttpGet]
        public ActionResult InventorySetter() {
            var sale = GetToday();
            if (sale == null) {
                return View("Error2", new Exception("Sale is not valid in the inventory setter. Contact with developer."));
            }

            //if (sale != null && sale.IsInventorySet) {
            //    return DetermineSaleDay(sale);
            //}

            List<DB.Inventory> invetories = db.Inventories
                                              .Include(c => c.Category)
                                              .ToList();
            var quantityNullStr = CookieIsInventoryEmpty;
            bool quantityNull = false;
            if (quantityNullStr == null) {
                quantityNull = invetories.All(n => n.Quantity == 0);
                CookieIsInventoryEmpty = quantityNull.ToString(); //saving it in cookie.
            }
            if (invetories.Count == 0 || quantityNull) {
                return View("Error2", new Exception("Inventory is not valid or inventory has no item. Please contact with your admin."));
            }

            ViewBag.SaleID = sale.SaleID;
            return View(invetories);
        }

        [HttpPost]
        public ActionResult InventorySetter(FormCollection forms) {
            int SaleID = int.Parse(Request["SaleID"]);

JustFood/Controllers/HomeController.cs
using System.Web.Mvc;
using JustFood.Modules.Mail;
using JustFood.Modules.StaticContents;

namespace JustFood.Controllers {
    public class HomeController : Controller {
        public ActionResult Index() {
            ViewBag.Message = "Management";
            return View();
        }
    }
}

JustFood/Areas/Sale/Views/Home/Create.cshtml
@model IEnumerable<Inventory>
@{
    ViewBag.Title = "Start Business " + JustFood.Modules.TimeZone.Zone.GetCurrentDate();
}
<h2>
    @ViewBag.Title
</h2>
@using (Html.BeginForm("Create", "Home", FormMethod.Post, new { id = "InventoryBox" })) {
    @Html.ValidationSummary(true)

    <fieldset>
        <hr />
        <label for="Cash">
            Cash:
        </label>
        <input name="Cash" value="" placeholder="Cash Changes In Hand" />
        @Html.ValidationMessage("Cash")
        <hr />
        <p>
            <input data-role="button" data-icon="save" type="submit" value="Start Business" />
            @Html.ActionLink("Back", "Index", new { Controller = "Home" }, new { data_role = "button", data_icon="arrow-l"})
        </p>
    </fieldset>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JustFood/Areas/Sale/Views/Home/Day.cshtml
@using JustFood.Modules.TimeZone
@model SaleDayView
@{
    ViewBag.Title = "Sale Of " + @Zone.GetDate(Model.SaleDated);
    var Summary = Model.GetSummary();
    bool IsSummary = Model.IsSummaryExist;
    int SaleID = ViewBag.SaleID;
}
<h2 style="text-align: center">
    @ViewBag.Title
</h2>
<div data-role="collapsible-set" data-theme="a" data-mini="true">
    <div data-role="collapsible" data-collapsed="true" data-theme="a" data-content-theme="c">
        <h3>
            Total Sold : <span id="total-sold">Tk. @Model.Sale.TotalSold</span> | Total Cash : Tk. <span id="total-acheived">@Model.Sale.TotalAcheived</span>
        </h3>
        <table>
            <tr>
                <td>
                    Total Discount
                </td>
                <td>
                    :
                </td>
                <td class="red">@(Model.Sale.Discount * -1)
                </td>
            </tr>
            <tr>
                <td>
                    Total Expenses
                </td>
                <td>
                    :
                </td>
                <td class="red">@(Model.Sale.OtherExpenses * -1)
                </td>
            </tr>
            <tr>
                <td>
                    Total Less
                </td>
                <td>
                    :
                </td>
                <td class="red">@(Model.Sale.TotalLess * -1)
                </td>
            </tr>
            <tr>
                <td>
                    Total Sold
                </td>
                <td>
                    :
                </td>
                <td class="green">@Model.Sale.TotalSold
                </td>
            </tr>
            <tr>
                <td class="bold">
                    Total
                </td>
                <td>
                    :
                </td>
                <td class="green bold">@(Model.Sale.TotalAcheived)
                </td>
            </tr>
        </table>
    </div>
</div>
<div>
    @Html.ActionLink("Inventory", "InventorySetter", new { Controller = "Home", SaleID = SaleID }, new { data_role = "button" })
    <div data-role="collapsible-set" data-corners="true">
        @Html.Partial("_AddProduct")
        @Html.Partial("_Expense")
        @Html.Partial("_Discount")
        @Html.Partial("_Requisition")
    </div>
</div>
<hr />
<div>
    @foreach (var item in Model.Salables) {
        <div data-role="controlgroup" data-theme="a">
            @if (!IsSummary) {
                <button data-role="button">@item.Category : 0</button>
            } else {

                var itemBySummaryCategory = Summary.FirstOrDefault(n => n.CategoryID == item.CategoryID);
                if (itemBySummaryCategory != null) {
                <a data-role="button" data-icon="bars" href="@Url.Action("DetailsOf", new { SaleID = @SaleID, CategoryID = item.CategoryID, time = DateTime.UtcNow })">@item.Category : @itemBySummaryCategory.SoldQuantity | Cash: @itemBySummaryCategory.CashInHand</a>
                    
                } else {
                <button data-role="button" data-theme="a" data-icon="bars">@item.Category : 0</button>
                    
                }
            }
            @Html.ActionLink("Add", "SaleItem", new { SaleID = @SaleID, CategoryID = item.CategoryID, time = @Zone.GetTimeDynamic()}, new { data_role = "button", data_icon = "plus", data_ajax_sync = "false" })
            @Html.ActionLink("Remove", "DiscardItem", new { SaleID = @SaleID, CategoryID = item.CategoryID, time = @Zone.GetTimeDynamic() }, new { data_role = "button", @class = "", data_icon = "delete" })
        </div>
    }
</div>
<p>
    @Html.ActionLink("Back", "Index", new { Controller = "Home" }, new { data_role = "button" })
</p>

JustFood/Areas/Sale/Views/Home/DetailsOf.cshtml
@model IList<JustFood.Models.DetailedSale>
@{
    ViewBag.Title = "Detailed Sale";
    var timeZone = (TimeZoneInfo)ViewBag.TimeZone;
}
<h2>@ViewBag.Title</h2>
<h2>@Model.FirstOrDefault().Category.Category1</h2>
@{
    Html.RenderPartial("_Back_Button");
}
<div  data-role="collapsible-set">
    @foreach (var item in Model) {
        string theme = "c";
        bool isDiscount = item.Discount != null && item.Discount > 0;
        //string collapsible = "";
        if (item.IsDiscard) {
            theme = "g";
        } else if (isDiscount) {
            theme = "h";
        }
        <div data-theme="@theme"  data-role="collapsible" data-collapsed="true" data-mini="true">
            <h3>
                @if (item.IsDiscard) {
                    <text>@Html.DisplayFor(modelItem => item.SoldAt) [Discarded]</text>
                } else if (item.Discount != null && item.Discount > 0) {
                    <text>@Html.DisplayFor(modelItem => item.SoldAt) [Discount : @item.Discount]</text>
                } else {
                    @Html.DisplayFor(modelItem => item.SoldAt)
                } | at @Html.DisplayTime(timeZone, item.Time)
            </h3>
            <div>
                <div>Processed by : @item.User.Name</div>
                @if (isDiscount) {
                    <div>Person : @item.DiscountPerson</div>
                    <div>Contact : @item.DiscountNumber</div>
                    <div>Discounted at : @item.Discount</div>
                }
                @if (item.Note != null) {
                    <div><strong>Notes : </strong>@item.Note</div>
                }
            </div>
        </div>
    }
</div>
<div data-role="footer" data-position="fixed" class="center" data-mini="true">
    <span>
        Cash: BDT. @ViewBag.Cash | Sold: @ViewBag.Items (PC) | Discount: BDT. @ViewBag.Discounts | Discards: @ViewBag.Discards
    </span>
</div>
@{
    Html.RenderPartial("_Back_Button");
}

JustFood/Areas/Sale/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Sale";
}

<h2>Sale</h2>


<ul data-role="listview" data-inset="true">
    <li data-role="list-divider">Reports</li>
    <li>@Html.ActionLink("Today's Report", "TodaysReport", "Reports")</li>
    <li>@Html.ActionLink("Reports", "Index", "Reports")</li>
    <li data-role="list-divider">Sale</li>
    <li>@Html.ActionLink("Today's", "Today", "Home")</li>
    <li>@Html.ActionLink("Yesterday's", "Create", "AccountBalance")</li>
    <li>@Html.ActionLink("Day Before Yesterday", "Create", "Expense")</li>
    <li>@Html.ActionLink("Week", "Create", "Expense")</li>
    <li>@Html.ActionLink("All", "Create", "Expense")</li>
    <li>@Html.ActionLink("Search", "Search", new {Controller = "AccountBalance"}, new {data_rel = "dialog", data_transition = "pop"})

</ul>

JustFood/Areas/Sale/Views/Home/InventorySetter.cshtml
@model IEnumerable<Inventory>
@{
    ViewBag.Title = "Create";
    var SaleID =  ViewBag.SaleID;
}
<h2>
    Current Stock Amount</h2>
@using (Html.BeginForm("InventorySetter", "Home", FormMethod.Post, new { id = "InventoryBox" })) {
    @Html.ValidationSummary(true)

    <fieldset>
        <hr />
        <input type="hidden" value="@SaleID" name="SaleID"/>
        @foreach (Inventory item in Model) {
            string category = item.Category.Category1;
            string fieldName = item.CategoryID.ToString();

            if (item.Quantity > 0) { 
            <div data-role="fieldcontain" class="@fieldName">
                <label for="@fieldName">@category</label>
                <input class="categoryInputs" type="range" name="@fieldName" placeholder="@category"
                           data-highlight="true" value="@item.Quantity" min="0" max="@item.Quantity" step="1" data-rel=".@fieldName" />
            </div>
            }
        }
        <p>
            <a href="javascript:void(0)" data-role="button" onclick="evaluateForm()" data-icon="check">
                Check</a>
            @Html.ActionLink("Back", "Index", new { Controller = "Home" }, new { data_role = "button",data_icon="arrow-l" })
        </p>
    </fieldset>
}
<script>
    function evaluateForm() {
        $(".categoryInputs").each(function () {
            if ($(this).val() === $(this).attr("max")) {
                var remove = $(this).attr("data-rel");
                $(remove).remove();

            }
        });
        $("#InventoryBox").submit();

    }
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JustFood/Areas/Sale/Views/Home/_AddProduct.cshtml
@using System.Collections
@using JustFood.Modules.TimeZone
@model SaleDayView
@{
    var quantityTypes = (IEnumerable<SelectListItem>) ViewBag.QuantityCategories;
    var categories = (IEnumerable<SelectListItem>) ViewBag.CategoryID;
}
@using (Html.BeginForm("AddProduct","Home")) {
    <fieldset data-role="collapsible" data-theme="a" data-content-theme="c" data-collapsed="true">
        <legend>Add Product</legend>
        @Html.Hidden("time", @Zone.GetTimeDynamic())
        @Html.Hidden("SaleID", Model.DiscountView.SaleID)
        

        @Html.LabelFor(m => m.AddProductView.CategoryID)
        @Html.DropDownList("CategoryID", categories)
        @Html.ValidationMessageFor(m => m.AddProductView.CategoryID)
        

        @Html.LabelFor(m => m.AddProductView.Quantity)
        @Html.TextBox("Quantity", 0 , new {type = "number"})
        @Html.ValidationMessageFor(m => m.AddProductView.Quantity)

        @Html.LabelFor(m => m.AddProductView.QuantityType)
        @Html.DropDownList("QuantityType", quantityTypes)
        @Html.ValidationMessageFor(m => m.AddProductView.CategoryID)

        @Html.LabelFor(m => m.AddProductView.Cost)
        @Html.TextBox("Cost", 0 , new {type = "number"})
        @Html.ValidationMessageFor(m => m.AddProductView.Cost)
        <p>
            <input type="submit" value="Add Product" data-role="button" />
        </p>
    </fieldset>
}

JustFood/Areas/Sale/Views/Home/_Discount.cshtml
@using JustFood.Modules.TimeZone
@model SaleDayView
@{
    var discountCategories = (IEnumerable<SelectListItem>)ViewBag.DiscountCategoryID;
}
@using (Html.BeginForm("Discount","Home")) {
    <fieldset data-role="collapsible" data-theme="a" data-content-theme="c" data-collapsed="true">
        <legend>Discount</legend>
        @Html.Hidden("time", @Zone.GetTimeDynamic())

        @Html.HiddenFor(m => m.DiscountView.SaleID)
        @Html.LabelFor(m => m.DiscountView.DiscountCategoryID)
        @Html.DropDownList("DiscountView.DiscountCategoryID", discountCategories)
        @Html.ValidationMessageFor(m => m.DiscountView.DiscountCategoryID)
        

        @Html.LabelFor(m => m.DiscountView.Name)
        @Html.EditorFor(m => m.DiscountView.Name)
        @Html.ValidationMessageFor(m => m.DiscountView.Name)

        @Html.LabelFor(m => m.DiscountView.Phone)
        @Html.EditorFor(m => m.DiscountView.Phone)
        @Html.ValidationMessageFor(m => m.DiscountView.Phone)

        @Html.LabelFor(m => m.DiscountView.Amount)
        @Html.EditorFor(m => m.DiscountView.Amount)
        @Html.ValidationMessageFor(m => m.DiscountView.Amount)
        
        @Html.LabelFor(m => m.DiscountView.Notes)
        @Html.EditorFor(m => m.DiscountView.Notes)
        @Html.ValidationMessageFor(m => m.DiscountView.Notes)
        <p>
            <input type="submit" value="Discounted" data-role="button" />
        </p>
    </fieldset>
        
}